services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/stock_tracker
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dQVwkB3D6pKo9rK+p21TaY5B8LROptIxiO2POWb81Bo=
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - stock-tracker

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=stock_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stock-tracker

volumes:
  postgres_data:

networks:
  stock-tracker:
    driver: bridge
